modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/AdvancedWipe/advancedtools/issues"
displayURL="https://www.curseforge.com/"
authors="Advancedwipe"
license="All rights reserved"

[[mods]]
	modId="advancedtools"
	version="${file.jarVersion}"
	displayName="AdvancedItems Mod"
	updateJSONURL="https://github.com/AdvancedWipe/advancedtools/issues"
	displayURL="https://www.curseforge.com/"
	logoFile="examplemod.png"
	credits="Thanks for this mod goes to Java, Forge and Minecraft"

	description='''
		Hey das ist etwas TEXT!!!
	'''
	
	[[dependencies.tutorialmod]]
    	modId="forge" 
    	mandatory=true
   		versionRange="[35,)"
    	ordering="NONE"
    	side="BOTH"

	[[dependencies.tutorialmod]]
    	modId="minecraft"
    	mandatory=true
    	versionRange="[1.16.4,1.17)"
    	ordering="NONE"
    	side="BOTH"
